### PR TITLE
AG-1395: Bump harmonized targets source version to pick up delimiter fix

### PR DESCRIPTION
**Pull request by JessterB**

### CODE REVIEW

**Review by jaclynbeck-sage — APPROVED** [review]

**Review by jaclynbeck-sage — COMMENTED** [review]
Actually I take back my approval until CI has re-run. I see this may have caused an issue with gene_info but want to let CI run again to make sure.

**Review by jaclynbeck-sage — CHANGES_REQUESTED** [review]
Yeah ok, it looks like something about the new file did something bad to gene_info processing. What is different about the new file?

**Comment by JessterB** [comment]
> Yeah ok, it looks like something about the new file did something bad to gene_info processing. What is different about the new file?

@jaclynbeck-sage I converted some semi-colon delimiters to commas, and forgot to escape them. I'll update the source and verify locally before I push up a new commit...sorry, I should have tested this locally first.

**Comment by jaclynbeck-sage** [comment]
Thanks. It looks like something is... off with this file (as well as its previous versions 48 and 47 which is as far back as I looked). The raw file has 1362 lines in it, but if you read it in as a CSV either programmatically or with Excel it only has 1162 lines (versions 48-50). For v47 it as 1334 lines / 1134 lines, so a 200-line discrepancy in both versions. 

Update: It looks like starting line 320, The Emory data has line breaks in the `Data_used_to_support_target_selection` column, which are escaped, so it does get read in successfully as one field. I guess that's ok? The raw file looks like:
```
320  ...,"Discovery quantitative proteomics of FrCx 
321    WPCNA of multiple and consensus cohorts
322    ANOVA",...
```
and the read-in string looks like: 
`"Discovery quantitative proteomics of FrCx \n WPCNA of multiple and consensus cohorts\n ANOVA"`

Is this something we're aware of/handle on the front end for display?

**Comment by JessterB** [comment]
> Thanks. It looks like something is... off with this file (as well as its previous versions 48 and 47 which is as far back as I looked). The raw file has 1362 lines in it, but if you read it in as a CSV either programmatically or with Excel it only has 1162 lines (versions 48-50). For v47 it as 1334 lines / 1134 lines, so a 200-line discrepancy in both versions.
> 
> Update: It looks like starting line 320, The Emory data has line breaks in the `Data_used_to_support_target_selection` column, which are escaped, so it does get read in successfully as one field. I guess that's ok? The raw file looks like:
> 
> ```
> 320  ...,"Discovery quantitative proteomics of FrCx 
> 321    WPCNA of multiple and consensus cohorts
> 322    ANOVA",...
> ```
> 
> and the read-in string looks like: `"Discovery quantitative proteomics of FrCx \n WPCNA of multiple and consensus cohorts\n ANOVA"`
> 
> Is this something we're aware of/handle on the front end for display?

@jaclynbeck-sage This seems to look ok in Agora in prod today (for the 2 genes I checked, RPH3A & STX1A): mv68 -> gene_info v56 -> harmonized targets v48

Screenshot 2024-10-28 at 1 11 24 PM

...but I could remove those /n since they are confusing and useless.

**Comment by jaclynbeck-sage** [comment]
> ...but I could remove those /n since they are confusing and useless.

Maybe? I'm guessing the line breaks are to indicate these are 3 separate items, not one single discovery method, so the way it's displaying in Agora right now isn't right because it looks like it's all mashed together in one sentence. I think probably the \n should be replaced with commas but also there's extra spaces around the \n that need to be dealt with in order for commas to look normal.

**Comment by JessterB** [comment]
@jaclynbeck-sage Those newlines go back to v1 of the source file from 2018 and no one has complained yet, but I went ahead and fixed it (in v51) by replacing the newlines with commas, and cleaning up extra spaces.

**Review by jaclynbeck-sage — APPROVED** [review]
Looks good, thank you!!

**Pull request merged**
