### PR TITLE
AG-825

### PR DESCRIPTION
**Pull request by JessterB**
* Update proteomics & proteomics_tmt column_renames
* Disable prod processing of TREAT-AD scores pending AG-565

### CODE REVIEW

**Review by j-hendrickson-sage — COMMENTED** [review]
Essentially, I see the removal "agora_rename:" block.  Why the removal now?

**Comment by JessterB** [comment]
Neither proteomics nor proteomics_tmt use a custom transform. Since there is no custom transform code expecting specific normalized field names, we can just alias the field names directly to what Agora needs in column_rename and they just pass through to the json file. This change simplifies the config, which is a good thing.

**Review by j-hendrickson-sage — APPROVED** [review]
I think we're good!

**Review by j-hendrickson-sage — APPROVED** [review]
Make sense to me; let me know of any specific checks or inclusions in the PR

**Review by j-hendrickson-sage — APPROVED** [review]

**Review by j-hendrickson-sage — APPROVED** [review]
good

**Review by j-hendrickson-sage — APPROVED** [review]

**Pull request merged**
